---
- name: Front configuration
  hosts: frontend
  become: yes
  tasks:
  - name: disable nginx
    ansible.builtin.command: dnf module disable nginx -y
  
  - name: disable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: disable nginx
    ansible.builtin.command: dnf install nginx -y
  