---
- name: Front configuration
  hosts: frontend
  become: yes
  tasks:
  - name: disable nginx
    ansible.builtin.command: dnf module disable nginx -y
  
  - name: enable nginx:1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.command: dnf install nginx -y
  
  - name: Remove file 
    ansible.builtin.file:
      path: /usr/share/nginx/html/* 
      state: absent
  
  - name: download frontend
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unarchieve frontend
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html 
      remote_src: yes
    
  - name: copy nginx.conf file
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes